// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlqbxbrodfifvzujuxql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhscWJ4YnJvZGZpZnZ6dWp1eHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzYzMDIsImV4cCI6MjA1NzU1MjMwMn0.ZlV77p1J90GvdygpX0854QQFyrdDfaV7vYqzI9P-LTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);